### ISSUE TITLE
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>

### ISSUE THREAD

**Issue by wuyy1234** [kazuto1011/dusty-gan#1]
Hi, thanks for sharing the code. 
But I met some errors when running the code to Setup KITTI Odometry. It seems that 'out = self.transform(out)' may cause the error. Below is the error message.

```
Dataset KITTIOdometry
    Number of datapoints: 19130
    Root location: ./data/data_odometry_velodyne/dusty-gan/sequences
  0%|                                                                                                                                                  | 0/299 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "process_kitti.py", line 219, in <module>
    angles = compute_avg_angles(loader)
  File "process_kitti.py", line 145, in compute_avg_angles
    for item in tqdm(loader):
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/userhome/dusty-gan-main/datasets/kitti.py", line 86, in __getitem__
    out = self.transform(out)
  File "/userhome/dusty-gan-main/datasets/kitti.py", line 74, in transform
    v = TF.resize(v, self.shape, Image.NEAREST)
  File "/root/miniconda3/envs/dpm-pc-gen/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 319, in resize
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>
```

**Comment by kazuto1011** [comment]
I found `TF.resize()` in torchvision<0.8.0 cannot accept `torch.Tensor`. What's a version of your installed torchvision?

**Comment by wuyy1234** [comment]
Hi, thanks for the reply. I have corrected the version of my torchvision. 
Best wishes!
